### ISSUE TITLE
YOLOP Segmentation results are not accurate, please have a look. Thanks a lot

### ISSUE THREAD

**Issue by lucianzhong** [l-sf/Linfer#2]
![Screenshot from 2023-11-10 19-17-24](https://github.com/l-sf/Linfer/assets/20123779/072647de-d4fe-438a-a88f-0f2683006080)

**Comment by l-sf** [comment]
推理、解码没有错误，这应该是他的模型的缺陷，这张图片效果比较差。我自己测试也是有的图片效果好，有的图片效果差。YOLOPv2效果会好一点，我还没有做。另外获取到mask之后可以做一些滤波之类的操作，应该会好一点。
![yolop_res4](https://github.com/l-sf/Linfer/assets/78126612/a329ff7f-f6a7-45ad-b159-097a0a308152)
![yolop_res6](https://github.com/l-sf/Linfer/assets/78126612/ded6c153-24be-443d-9f14-fddbd31867cb)

**Comment by lucianzhong** [comment]
谢谢回复，请问下您那边测试下来推荐什么模型，范化性比较好？

**Comment by l-sf** [comment]
实在不好意思，其实我也不太了解可行驶区域分割这个领域，我只是看到YOLOP一下能做三个任务，比较好玩，就部署了一下。我后面看到YOLOPv2效果好一些，可以试试吧，我也不太清楚具体的。

**Comment by lucianzhong** [comment]
收到，谢谢回复
