### ISSUE TITLE
OSTrack、LightTrack model

### ISSUE THREAD

**Issue by fubai3** [l-sf/Linfer#3]
Hello, OSTrack, LightTrack two single target tracking model link can not open

**Comment by l-sf** [comment]
Hi, thanks for your interest in my work.

What do you mean by the model link? I didn't understand what you meant.

The link of repo that only includes single target tracking is [Track-trt](https://github.com/l-sf/Track-trt), If you only use single target tracking, you can refer to this repo, which may be simpler to use.

The onnx models of OSTrack and LightTrack can be got from [google driver](https://drive.google.com/drive/folders/16ZqDaxlWm1aDXQsjsxLS7yFL0YqzHbxT?usp=sharing) , and if you have modified the model and want to export onnx yourself, you can refer to [ostrack](https://github.com/l-sf/Track-trt/blob/main/ostrack/README.md)  and [lighttrack](https://github.com/l-sf/Track-trt/blob/main/lighttrack/README.md).

![image](https://github.com/l-sf/Linfer/assets/78126612/2bef5860-9dff-4223-be11-21b8c10227b9)

Best wishes.

**Comment by fubai3** [comment]
Okay, I found it. The link wasn't open until now. Thank you
